### PR TITLE
Added Azure Pipelines scheduled weekly build

### PR DESCRIPTION
**Pull request by deqenq**

### CODE REVIEW

**Comment by pascalberger** [comment]
Just for your info: The scheduled builds probably will stop running if there's no activity in the repo for a certain amount of time. There're some limitations in Azure Pipelines regarding this

**Comment by deqenq** [comment]
@pascalberger Thank you for pointing it out. According to the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml), there is option `always`:

`always: boolean # whether to always run the pipeline or only if there have been source code changes since the last run. The default is false`

And there are some notes about setting schedule in yaml AND in pipelines UI. 
What I want to achieve is that after some time of inactivity, the Azure Pipelines badges in readme file are telling "never built", so weekly build could refresh badge status. 

If you are right, then I will have to add new wget switch to wget alias each week to refresh those badges :-)

**Comment by daveaglick** [comment]
For what it's worth, I've had reasonable success triggering Azure DevOps builds on a schedule using Flow. It works great except for once or twice a year when Flow suddenly stops authenticating to DevOps and you have to either rebuild the Flow or wait for the Flow team to work out their OAuth issues.

**Comment by deqenq** [comment]
@daveaglick Thanks for sharing the experience. There is always something new to learn.

**Comment by pascalberger** [comment]
@deqenq `always` option won't help you, since we probably don't have enough visits to Azure DevOps to prevent it going dormant and misses scheduling the build.

The only thing to keep it alive is to have visits to any page, any API calls or changes in the GitHub repo. Triggering by API works finde as @daveaglick pointed out, as would a job regularly calling a site or API (e.g. for one account I've a build monitor running which polls build status through REST API which also keeps it alive).

**Comment by deqenq** [comment]
@pascalberger If I understand correctly, then calling periodically (eg. on weekly basis) the [build status for Windows](https://dev.azure.com/cake-contrib/Cake.Wget/_apis/build/status/cake-contrib.Cake.Wget%20-%20Windows?branchName=master) endpoint keeps the badge for Windows Pipelines alive?

**Comment by pascalberger** [comment]
What I was talking about is that an Azure DevOps oganization goes dormant after five minutes of inactivity, which also includes the system responsible for executing the scheduled build.

I would expect showing a badge, would call the API and awake the Azure DevOps organization. So I don't see a reason why a badge should show the wrong value. I never experienced this issue with the badges on my repos (e.g. [Cake.AzureDevOps](https://github.com/cake-contrib/Cake.AzureDevOps) was last build 17 days ago and build status shows the correct value. Are you sure this is the issue and not something else?

**Comment by deqenq** [comment]
@pascalberger Sorry for late repsonse but I tried to search some more information and I suspect that the retention policy in pipeline settings (_Project settings - Pipelines - Retention policy_) can cause that after 30 days (which is default value for `Days to keep artifacts and attachments`) the badge forgets its status (and clicking on badge leads to `No build were found`). My testing project [ApTest](https://github.com/deqenq/ApTest) has not been updated more than 30 days and badges for Azure Pipelines are in `never built` status. This Cake.Wget project was updated on 2019-07-13 and after more than 30 days it had also `never built` status until I manualy started the pipelines.

**Comment by deqenq** [comment]
@pascalberger Seems that the retention policy mentioned in previous post is really causing Azure Pipelines status "never built" after 30 days of inactivity. Currently also your repository [Cake.AzureDevOps](https://github.com/cake-contrib/Cake.AzureDevOps) has badges in "never built" status. So I will close this PR without merge.

**Pull request closed without merging**
